name: Build Godot Project

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux/X11, Windows Desktop, macOS, Android, Web]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: PVZ
          preset: ${{ matrix.platform }}
          debugMode: "true"
          package: "true"
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.artifact }}