name: Build Godot Project

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux/X11, Windows Desktop, macOS, Android, Web]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Godot
        uses: Vitorgus/Setup-Godot@v1.1.1
        with:
          godot-version: 4.2.1
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export "Web" ./build/web/index.html     
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Client - web
          path: build/web